Feature/edit tasks
maosan132/javascript-TODO-app pull request #4
Opened 2021-03-06 23:22 UTC by maosan132

# Description

Hello pals, I am re-submitting this pull request so everybody can give support and suggestions for making this project better, so it can be approved. Any suggestions will be fully appreciated. 

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-03-07 00:32 UTC, MuriloRoque requested changes
## Status: Changes requested :red_circle: 

### Hello @maosan132 :wave: 

### Good job making some of the requested changes from the previous TSE. I really like your app, it's beautiful and functional! There are just some more things we need to fix before moving on:

- [ ] Please don't open another PR, you can continue using this one for the next review.
- [ ] Your live link is still redirecting to a "Not Found" page, please change it.
- [ ] Check my comments in your code, there are some commented pieces of code.

Kindly make the requested changes and submit them for another review, please :pray: 

I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2021-03-07 00:32 UTC, MuriloRoque commented on dist/index.html
> +  </template> -->
- [ ] There are still some commented pieces of code.

2021-03-07 00:32 UTC, MuriloRoque commented on src/helper.js
> +};
- [ ] There are still some commented pieces of code.

2021-03-07 00:32 UTC, MuriloRoque commented on src/project-model.js
> +// }
- [ ] There are still some commented pieces of code.

2021-03-07 00:32 UTC, MuriloRoque commented on src/task-model.js
> +// }
- [ ] There are still some commented pieces of code.

2021-03-07 04:30 UTC, maosan132 commented
Hi  MuriloRoque, thanks for your help. I have fixed everything.

2021-03-08 00:40 UTC, bellom approved these changes
## Hi @maosan132  :clap: 

**Great work making all the necessary corrections from the previous review.**

# Status: Approved 👍 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next project :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2021-03-14 04:04 UTC, maosan132 commented
Thanks so much

2021-03-14 04:04 UTC, closed without merging